# Generated by Django 3.2.12 on 2022-02-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220224_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
