# Generated by Django 3.2.12 on 2022-02-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220224_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
